#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define SUCCESS 0
#define ERR_INVALID_CMD 100
#define ERR_PATH_NOT_FOUND 101
#define ERR_STORAGE_SERVER_DOWN 102
#define ERR_SOCKET_FAILED 103
#define ERR_ALREADY_EXISTS 104
#define ERR_FILE_DELETION_FAILED 105
#define ERR_FILE_CREATION_FAILED 106
#define ERR_READ_FAILED 107
#define ERR_WRITE_FAILED 108
#define ERR_STREAM_FAILED 109
#define ERR_COPY_FAILED 110
#define ERR_GET_INFO_FAILED 111
#define ERR_SEND_FAILED 112
#define ERR_RECV_FAILED 113
#define ERR_CONNECTION_FAILED 114
#define ERR_FILE_NOT_FOUND 115
#define ERR_INVALID_ADDRESS 116
#define ERR_MAX_WRITE_LIMIT 117
#define ERR_CONNECTION_TO_SS 118
#define ERR_NO_RESPONSE 119
#define ERR_OPENDIR 120
#define ERR_OPEN_FILE 121
#define ERR_DIR_CREATION_FAILED 122
#define ERR_DIR_DELETION_FAILED 123
#define ERR_FILESTAT_FAILED 124
#define ERR_CLIENT_DISCONNECTED 125
#define ERR_SETSOCKOPT_FAILED 126
#define ERR_BIND_FAILED 127
#define ERR_LISTEN_FAILED 128
#define ERR_ACCEPT_FAILED 129

#endif
